### ISSUE TITLE
What's this bro

### ISSUE THREAD

**Issue by Blazepoint5** [calamity-inc/Stand-Launchpad#11]
Hey bro i came here cause of the fsr mod and i downloaded the launchpad.exe but says this when i launch  
![20240110_083014](https://github.com/calamity-inc/Stand-Launchpad/assets/154701981/01929b66-8f04-4330-826b-3e2fa099c9a8)

How do i fix it and please bro please show me how to make the fsr mod work with your launch pad thingi i dont understanding a thing, idk this kind of stuff about compiling visual studio thing.

Please man guide me to make the mod work with your help

**Comment by Sainan** [comment]
All the information you need is in the error message.

**Comment by Blazepoint5** [comment]
> All the information you need is in the error message.

Cant you make and update to support 1.67 build since its on that version that rockstar did a patch about the game not reading dll files in the game root folder? If its not possible i appreciate your work man thanks

**Comment by Sainan** [comment]
Stand only supports the latest game version at any given time. You are free to use the Launchpad with other DLLs, even on older game builds, just don't try to inject Stand.

**Comment by Blazepoint5** [comment]
> Stand only supports the latest game version at any given time. You are free to use the Launchpad with other DLLs, even on older game builds, just don't try to inject Stand.

Why shouldn't i try to inject stand, enlighten me.

**Comment by Sainan** [comment]
> Stand only supports the latest game version at any given time.
