### ISSUE TITLE
RGL launch doesn't work at all if launcher is closed

### ISSUE THREAD

**Issue by alessandromrc** [calamity-inc/Stand-Launchpad#13]
The fix that has been done doesn't work at all when the launcher is closed and will return an error about the launcher being closed... Firstly check if the launcher is currently running and if not, launch it up and then launch the game.

![image](https://github.com/calamity-inc/Stand-Launchpad/assets/66976091/cafa528f-a80e-44cb-8cd1-ba0e4d7ff91a)

**Comment by Sainan** [comment]
I am unable to reproduce this. The launcher gets started if it wasn't already running.

**Comment by alessandromrc** [comment]
I guess the easiest solution either ways is to start up the launcher without the game argument and then execute the actual launch of the game... It would take literally nothing but it ensures the fact of it working. (That happened to me after the first launch right after having downloaded the RGL update, knowing it can break easily, it would make sense to add this anyway).

**Comment by Sainan** [comment]
Feel free to submit a PR, but as I am unable to reproduce this issue, I won't be able to "fix" it.

**Comment by alessandromrc** [comment]
Looking at the changes the launcher got it seems like they enabled the flag "modScan" within the metadata the launcher gets from their backend, thinking about directly patching that using a DLL might make sense as it would prevent future issues with the feature... I am sure they will implement it even when launching the game directly. 

More about it [here](https://gamedownloads-rockstargames-com.akamaized.net/public/title_metadata.json)
