### ISSUE TITLE
Only allow 1 instance to be open at once

### ISSUE THREAD

**Issue by Sainan** [calamity-inc/Stand-Launchpad#5]
Example of how to do this according to GPT:

```C#
using System.Threading;

class Program
{
    static void Main()
    {
        bool createdNew;
        Mutex mutex = new Mutex(true, "MyUniqueMutexName", out createdNew);
        if (!createdNew)
        {
            // Another instance of the application is already running
            return;
        }

        // Run your application here

        mutex.ReleaseMutex();
    }
}
```

**Comment by alessandromrc** [comment]
Cannot we just scan for process names and if there's a match it means there's another instance like here: https://github.com/calamity-inc/Stand-Launchpad/pull/4. Also I think that mutex way of doing it might create issues eg. if the launchpad crashes and doesn't release it.

**Comment by alessandromrc** [comment]
@Sainan are you sure that the file will get deleted even if the launchpad crashes? Otherwise we might have issues with a lot of users not being able to open the launcher if eg they power off their pc without closing the launchpad before :/

**Comment by Sainan** [comment]
I am aware that might be an issue. I will amend the troubleshooting page accordingly.

**Comment by alessandromrc** [comment]
I'm still wondering why the implementation I made wasn't being actually used as it would never have these issues... It might just slow down a little the opening of the launchpad but will surely make no issues with bad shutdown or anything else related to the matter.

**Comment by Sainan** [comment]
The problem is that it could be "Stand Launchpad.exe", "Stand.Launchpad.exe", "Stand_Launchpad.exe". Not to mention if the user tries to be funny like "Femboy Launcher.exe".

Also the abrupt close issue should be fixed now with my latest commit.

**Comment by alessandromrc** [comment]
If you want to keep that way I would have used a try-catch block with the finally including the delete block file and also check for the block file date that if it is older than eg 1 day it should be ignored. Anyway I would have preferred the launcher to break on a process name change than making it impossible to open even to normal users. Also we could add the process name to the config file so the users can change it to whatever they want and call it a day forever.

**Comment by Sainan** [comment]
Sounds needlessly overengineered.

**Comment by alessandromrc** [comment]
What if we use something like this:

```cpp
            int currentProcessId = Process.GetCurrentProcess().Id;

            foreach (Process process in Process.GetProcesses())
            {
                try
                {
                    if (process.MainModule != null && process.MainModule.FileVersionInfo != null)
                    {
                        if (process.MainModule.FileVersionInfo.ProductName == "Stand Launchpad" && process.Id != currentProcessId)
                        {
                            showMessageBox("There's another instance of the Stand Launchpad already running!");
                            Environment.Exit(1);
                            break;
                        }
                    }
                }
                catch (Exception)
                {
                }
            }
```

The try-catch is needed to avoid issues with higher privilege processes that might block the access of MainModule infos

**Comment by Sainan** [comment]
The reason I use a try-catch is as a ghetto way of detecting if the file is locked.

**Comment by alessandromrc** [comment]
I wonder if there's a parameter within the API that returns if it is locked tho.

**Comment by Sainan** [comment]
It works. ¯\\\_(ツ)\_/¯

**Comment by alessandromrc** [comment]
Whatever ¯\\_(ツ)_/¯... I still don't feel safe about that way but if you think it will work we can leave it like that.

**Comment by Sainan** [comment]
It works that way because it makes logical sense and I tested it. If there's an issue, real-world usage will show it.

**Comment by alessandromrc** [comment]
> It works that way because it makes logical sense and I tested it. If there's an issue, real-world usage will show it.

Defo agreeing with you. Also we already have other implementations ready here that can be used too.
